### ISSUE TITLE
ICS problem

### ISSUE THREAD

**Issue by mdecaro** [Liturgical-Calendar/LiturgicalCalendarAPI#66]
Whenever an attempt is made to generate ICS output, an error occurs.

There is no obvious error, but if the ICS file is examined, here is the output:

<br />
<b>Warning</b>:  Undefined property: stdClass::$published_at in <b>/var/www/vhosts/johnromanodorazio.com/httpdocs/LiturgicalCalendar/LitCalEngine.php</b> on line <b>2731</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function ParseColorString() in /var/www/vhosts/johnromanodorazio.com/httpdocs/LiturgicalCalendar/LitCalEngine.php:2769
Stack trace:
#0 /var/www/vhosts/johnromanodorazio.com/httpdocs/LiturgicalCalendar/LitCalEngine.php(3073): LitCalEngine-&gt;generateResponse()
#1 /var/www/vhosts/johnromanodorazio.com/httpdocs/LiturgicalCalendar/LitCalEngine.php(73): LitCalEngine-&gt;Init()
#2 {main}
  thrown in <b>/var/www/vhosts/johnromanodorazio.com/httpdocs/LiturgicalCalendar/LitCalEngine.php</b> on line <b>2769</b><br />

<br /><br />
Regardless of the endpoint, I have tried many variations, as long as ICS is return type, the error occurs.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser safari and chrome

**Comment by JohnRDOrazio** [comment]
Thanks for letting me know, I have been doing a lot of rewriting and refactoring to make the code cleaner, easier to read, easier to maintain, and easier to extend in different languages and for different national and local calendars.

In the last few days I have also been moving away from PHP arrays for translations, to gettext and JSON based translations, which are much easier to maintain through weblate and much more expandable to different languages.

I'm not surprised that there's a hiccup here and there, since so much has been changed. I split the single monolithic PHP file into a number of classes and enum-type classes. I've grouped functions together into separate classes based on their purpose. So something is probably calling something that has probably moved. I'll look into it tonight or tomorrow.

**Comment by mdecaro** [comment]
Excellent, thx

**Comment by mdecaro** [comment]
Mostly fixed by making ParseColorString and ColorToHex static.

**Comment by JohnRDOrazio** [comment]
Fixed in commit d8dd902

* update `$GithubReleasesAPI` variable to reflect the new URL for the Github repo
* replace deprecated `LITCAL_MESSAGES::_G()` method with the newly created `LitGrade::i18n()` method that works with `gettext`
* replace hardcoded string value that was passed into the deprecated `LITCAL_MESSAGES::_G()` method with the enum equivalent as required by the newly created `LitGrade::i18n()` method
* fix value being passed into the `produceIcal` method: need to pass `$infoObj->obj` not just `$infoObj` (either that or we need to access the `obj` property from within `produceIcal` method)
